
Events Event \
 < 1, 1,'New Years'>,
 < 1,28,'HW0 Due'>,
 < 1,31,'MP0 Due'>,
 < 2, 4,'HW1 Due'>,
 < 2,11,'MP1 Due'>,         
 < 2,21,'MP2 Due'>,          
 < 2,25,'HW2 Due'>,
 < 2,27,'EXAM I' >,
 < 3, 1,'MP3 Due'>,
 < 3,18,'HW3 Due'>, 
 < 3,20,'MP4 Due'>,
 < 3,25,'Spring Break'>,
 < 4, 1,'Project Signup'>,
 < 4, 8,'HW4 Due'>,
 < 4,10,'EXAM II'>,
 < 4,15,'MP5 Due'>,
 < 4,22,'Proj. Writeup'>,
 < 4,29,'Proj. Demos'>,
 < 5, 6,'Proj. Submit'>,
 < 5, 8,'HW5 Due'>,
 <12,25,'XMAS'>

numrec dw LENGTHOF Events ; How many records are in the database

lookahead dw 14 ; How many days to look ahead

